version: "3"

services:
  postgres:
    image: postgres:16
    container_name: CHANGEME_postgres
    env_file: ".env"
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - 6379:6379

  app: &app
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./compose/changeme/Dockerfile
    image: CHANGEME
    container_name: CHANGEME_app
    entrypoint: /entrypoint
    command: /start
    env_file: ".env"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app/

volumes:
  pg_data: {}
